
ahli_ahkCommList(){
	clist =
(LTrim
Hotkey,
Sleep,
Suspend,
Exit,
ExitApp,
OnExit,
InputBox,V_var1,
Progress,
SplashImage,
SplashTextOn,
SplashTextOff,
TrayTip,
SetEnv,V_var1,
EnvGet,
Random,V_var1,
Input,
KeyWait,
SendRaw,
SendInput,
SendPlay,
SendEvent,
SendMode,
BlockInput,
Gui,
GuiControlGet,V_var1,
GuiControl,
WinClose,
WinActivate,
WinWait,
WinWaitActive,
WinWaitClose,
WinWaitNotActive,
ControlSend,
WinShow,
StringLen,V_var1,
Send,
ControlClick,
Run,
RunWait,
RunAs,
Process,
WinMinimizeAll,
WinMinimizeAllUndo,
WinExist("")
WinActive("")
WinKill,
WinGet,V_var1,
WinGetClass,V_var1,
WinGetTitle,V_var1,
WinGetPos,V_var1,V_var2,V_var3,V_var4,
WinGetActiveStats,V_var1,V_var2,V_var3,V_var4,V_var5
WinMove,
WinHide,
WinSet,
WinSetTitle,
DetectHiddenWindows,
DetectHiddenText,
SetTitleMatchMode,
SetWinDelay,
SetWorkingDir,
WinGetActiveTitle,V_var1
WinActivateBottom,
WinMaximize,
WinMinimize,
WinRestore,
StatusBarWait,
GroupAdd,
GroupActivate,
GroupClose,
GroupDeactivate,
StatusBarGetText,
FileExist("")
FileSetAttrib,
RegExMatch("","")
RegExReplace("","")
StringLen,V_var1,
StringMid,V_var1,
StringSplit,V_var,
StringReplace,V_var1,
StringLower,V_var1,
StringUpper,V_var1,
StringCaseSense,
StringLeft,V_var1,
StringRight,V_var1,
StringTrimLeft,V_var1,
StringTrimRight,V_var1,
StringGetPos,V_var1,
MouseGetPos,V_var1,
MouseMove,
MouseClick,
MouseClickDrag,
Click,
Sort,V_var1,
WinGetText,V_var1,
WinMenuSelectItem,
Pause,
IsLabel("")
IsFunc("")
Gosub,
Menu,
SoundPlay,
FileCopyDir,
FileMoveDir,
FileCopy,
FileMove,
FileAppend,
FormatTime,V_var1,
ListVars,
OutputDebug,
ListLines,
SysGet,V_var1,
ControlGet,V_var1,
ControlGetText,V_var1,
Control,
ControlGetFocus,V_var1,
ControlGetPos,V_var1,V_var2,V_var3,V_var4,
ControlFocus,
ControlMove,
ControlSetText,
SetControlDelay,
DriveGet,V_var1,
Drive,
FileCreateShortcut,
FileGetShortcut,
FileGetAttrib,V_var1,
FileGetTime,V_var1,
FileGetVersion,V_var1,
FileSetTime,
DriveSpaceFree,V_var1,
FileRemoveDir,
FileCreateDir,
FileRecycle,
FileRecycleEmpty,
FileDelete,
FileGetSize,V_var1,
FileRead,V_var1,
FileReadLine,V_var1,
SplitPath,
FileEncoding,
IniWrite,
IniDelete,
IniRead,V_var1,
EnvAdd,
EnvSub,
EnvMult,
EnvDiv,
SetFormat,integer,H
Transform,V_var1,
FileSelectFile,V_var1,
FileSelectFolder,V_var1,
URLDownloadToFile,
ToolTip,
MsgBox,
SoundGet,V_var1,
SoundGetWaveVolume,V_var1,
SoundSetWaveVolume,
SoundBeep,
Shutdown,
RegRead,V_var1,
KeyHistory,
ListHotkeys,
Reload,
ClipWait,
SetTimer,G_subroutine1
PixelGetColor,V_var1,
ImageSearch,V_var1,V_var2,
PixelSearch,V_var1,V_var2,
CoordMode,
AutoTrim,
PostMessage,
SendMessage,
SetKeyDelay,
SetStoreCapslockMode,
SetCapsLockState,
SetScrollLockState,
SetNumLockState,
SetMouseDelay,
SetDefaultMouseSpeed,
GetKeyState,V_var1,
IfEqual,V_var1,  ,{ }
IfNotEqual,V_var1,  ,{ }
IfGreater,V_var1,  ,{ }
IfGreaterOrEqual,V_var1,  ,{ }
IfLess,V_var1,  ,{ }
IfLessOrEqual,V_var1,  ,{ }
IfWinActive, , , , ,{ }
IfWinNotActive, , , , ,{ }
IfWinExist, , , , ,{ }
IfWinNotExist, , , , ,{ }
IfExist,  ,{ }
IfNotExist,  ,{ }
IfMsgBox,Yes ,{ }
IfInString,V_var1,  ,{ }
IfNotInString,V_var1,  ,{ }
If V_var1 in value1,value2 { }
If V_var1 contains value1,value2 { }
If V_var1 between Low and High { }
If V_var1 is number { }
)

	return clist
}
