
syfl_systemHotkeyObjInsert(){

	glob_systemHotkeyObj.Insert("Ctrl+Space", "入力補完を表示`n&popList")
	glob_systemHotkeyObj.Insert("Alt+T", "%%や##でくくられた値を展開`n&textOut")
	glob_systemHotkeyObj.Insert("Alt+P", "アイテムのリンク先を表示`n&pathLink")
	glob_systemHotkeyObj.Insert("Alt+Shift+P", "ショートカットのリンク先を表示`n&shortCutPath")
	glob_systemHotkeyObj.Insert("Alt+Left", "フォルダの１つ上の階層にする`n&backOneDir")
	glob_systemHotkeyObj.Insert("Alt+Right", "１つ上の階層にしたフォルダを元に戻す`n&reBackOneDir")
	glob_systemHotkeyObj.Insert("Alt+F", "絶対パスにする`n&fullPath")
	glob_systemHotkeyObj.Insert("Alt+R", "相対パスにする`n&relativePath")
	glob_systemHotkeyObj.Insert("Alt+Semicolon", "最後の単語を先頭にする`n&lastAsHead")
	glob_systemHotkeyObj.Insert("Alt+2", "ファイルパスをダブルクウォーテで囲む`n&doubleQuouteCustom")
	glob_systemHotkeyObj.Insert("Alt+3", "文字を##で囲み、￥をつける`n&sharpssCustom")
	glob_systemHotkeyObj.Insert("Alt+5", "文字を%%で囲む`n&parsentss")
	glob_systemHotkeyObj.Insert("Ctrl+N", "アイテムの新規登録のＧＵＩを表示`n&newItem")
	glob_systemHotkeyObj.Insert("Ctrl+Shift+N", "ショートカットキーの新規登録のＧＵＩを表示`n&hotkeyOnTextNew")
	glob_systemHotkeyObj.Insert("Alt+Enter", "アイテムの編集`n引数がカラならアイテム一覧のＧＵＩを表示`n&editItem")
	glob_systemHotkeyObj.Insert("Alt+Shift+Enter", "ショートカットキーの編集`n引数がカラならキーの一覧のＧＵＩを表示`n&hotkeyOnTextEdit")
	glob_systemHotkeyObj.Insert("Alt+o", "アイテムやファイルの実行内容を確認する`n&openConfirm")
	glob_systemHotkeyObj.Insert("Alt+Shift+o", "アイテムやファイルの実行内容を確認する`n&openConfirmOneLine")
	glob_systemHotkeyObj.Insert("Alt+C", "テキストの文字列をカラにする`n&cleanText")
	glob_systemHotkeyObj.Insert("Ctrl+1", "ストック青の１のテキストを利用して実行`n&collabText 6 1")
	glob_systemHotkeyObj.Insert("Ctrl+2", "ストック青の２のテキストを利用して実行`n&collabText 6 2")
	glob_systemHotkeyObj.Insert("Ctrl+3", "ストック青の３のテキストを利用して実行`n&collabText 6 3")
	glob_systemHotkeyObj.Insert("Ctrl+4", "ストック青の４のテキストを利用して実行`n&collabText 6 4")
	glob_systemHotkeyObj.Insert("Ctrl+5", "ストック青の５のテキストを利用して実行`n&collabText 6 5")
	glob_systemHotkeyObj.Insert("Ctrl+6", "ストック青の６のテキストを利用して実行`n&collabText 6 6")
	glob_systemHotkeyObj.Insert("Ctrl+7", "ストック青の７のテキストを利用して実行`n&collabText 6 7")
	glob_systemHotkeyObj.Insert("Ctrl+8", "ストック青の８のテキストを利用して実行`n&collabText 6 8")
	glob_systemHotkeyObj.Insert("Ctrl+9", "ストック青の９のテキストを利用して実行`n&collabText 6 9")
	glob_systemHotkeyObj.Insert("Ctrl+0", "ストック青の１０のテキストを利用して実行`n&collabText 6 10")
	glob_systemHotkeyObj.Insert("Ctrl+Shift+1", "ストック緑の１のテキストを利用して実行`n&collabText 7 1")
	glob_systemHotkeyObj.Insert("Ctrl+Shift+2", "ストック緑の２のテキストを利用して実行`n&collabText 7 2")
	glob_systemHotkeyObj.Insert("Ctrl+Shift+3", "ストック緑の３のテキストを利用して実行`n&collabText 7 3")
	glob_systemHotkeyObj.Insert("Ctrl+Shift+4", "ストック緑の４のテキストを利用して実行`n&collabText 7 4")
	glob_systemHotkeyObj.Insert("Ctrl+Shift+5", "ストック緑の５のテキストを利用して実行`n&collabText 7 5")
	glob_systemHotkeyObj.Insert("Ctrl+Shift+6", "ストック緑の６のテキストを利用して実行`n&collabText 7 6")
	glob_systemHotkeyObj.Insert("Ctrl+Shift+7", "ストック緑の７のテキストを利用して実行`n&collabText 7 7")
	glob_systemHotkeyObj.Insert("Ctrl+Shift+8", "ストック緑の８のテキストを利用して実行`n&collabText 7 8")
	glob_systemHotkeyObj.Insert("Ctrl+Shift+9", "ストック緑の９のテキストを利用して実行`n&collabText 7 9")
	glob_systemHotkeyObj.Insert("Ctrl+Shift+0", "ストック緑の１０のテキストを利用して実行`n&collabText 7 10")
	glob_systemHotkeyObj.Insert("Ctrl+Alt+1", "テキスト１を利用して実行`n&collabText 1")
	glob_systemHotkeyObj.Insert("Ctrl+Alt+2", "テキスト２を利用して実行`n&collabText 2")
	glob_systemHotkeyObj.Insert("Ctrl+Alt+3", "テキスト３を利用して実行`n&collabText 3")
	glob_systemHotkeyObj.Insert("Ctrl+Alt+4", "分割テキスト１を利用して実行`n&collabText 4")
	glob_systemHotkeyObj.Insert("Ctrl+Alt+5", "分割テキスト２を利用して実行`n&collabText 5")
}
